# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d123544012a59e9b16ae54b263d748026d721b9902df5706a98ca41bf715706f23e37729b8ac7e5e618915ad8f22e82ad053e18f31da770ec0a2e442bae3a762

test:
  secret_key_base: d9ac99891b791dddd5f1bb225de1d5e88c14f75ee57f6e1858ceca39006b4f6c20c43e1c766ca0db4d31f2953d70b6793ccce73572f05c5367f7ee68d73887f2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
